### ISSUE TITLE
Error for device type for index #3

### ISSUE THREAD

**Issue by harshikanu** [hpanwar08/sentiment-analysis-torchtext#1]
Hi,

I was trying to execute your code as-is. I was facing the following error:

--- Train GRU Pool ---
HBox(children=(IntProgress(value=0, max=5), HTML(value='')))
HBox(children=(IntProgress(value=0, max=2467), HTML(value='')))
Traceback (most recent call last):
  File "Torchtext_alerts.py", line 259, in <module>
    fit(model=m, train_dl=train_batch_it, val_dl=val_batch_it, loss_fn=F.nll_loss, opt=opt, epochs=5)
  File "Torchtext_alerts.py", line 219, in fit
    pred = model(X, lengths)
  File "C:\Users\Morpheus\.virtualenvs\backend-36r_k6fO\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "Torchtext_alerts.py", line 151, in forward
    embs = self.emb(seq)
  File "C:\Users\Morpheus\.virtualenvs\backend-36r_k6fO\lib\site-packages\torch\nn\modules\module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "C:\Users\Morpheus\.virtualenvs\backend-36r_k6fO\lib\site-packages\torch\nn\modules\sparse.py", line 114, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "C:\Users\Morpheus\.virtualenvs\backend-36r_k6fO\lib\site-packages\torch\nn\functional.py", line 1484, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected object of device type cuda but got device type cpu for argument
#3 'index' in call to _th_index_select

I tried everything i could to fix it, but still seem to run into the same error.

Let me know if you could help me fix this error. 

I have lates CUDA version : 10.2

**Comment by hpanwar08** [comment]
@harshikanu it seems like torch is expecting data to be in gpu, but your data is in cpu. You need to transfer your tensors to gpu. Can you show the code where it is throwing error?

**Comment by harshikanu** [comment]
Thanks for getting back,

The code was throwing an error in these lines 
"File "Torchtext_alerts.py", line 259, in
fit(model=m, train_dl=train_batch_it, val_dl=val_batch_it, loss_fn=F.nll_loss, opt=opt, epochs=5)
File "Torchtext_alerts.py", line 219, in fit
pred = model(X, lengths)"

Also, the sentiment anallysis using ignite worked just fine. 
I wanted to know from you how do I predict the sentiment of a corpus of text that I have ?

Thanks!

**Comment by hpanwar08** [comment]
What is your pytorch and torchtext version. This notebook was written for pytorch 0.4 and torchtext 0.2.3.
Check whether trainds.fields['SentimentText'].vocab.vectors is gpu tensor or cpu tensor.

For prediction on a corpus do the same preprocessing as you did for training data, then pass each sample through the model

```
model.eval()
pred = model(X, lengths)
pred_idx = torch.max(pred, dim=1)[1]
# convert the pred_idx to your label
```
